DROP TABLE QIngredientSupplier
DROP TABLE QIngredientIngOrder
DROP TABLE QMenuItemIngredient
DROP TABLE QOrderMenuItem
DROP TABLE IngredientOrder
DROP TABLE InShopShift
DROP TABLE InStorePay
DROP TABLE PickupOrder
DROP TABLE DeliveryOrder
DROP TABLE PhoneOrder
DROP TABLE WalkInOrder
DROP TABLE DriverShift
DROP TABLE DriverPay
DROP TABLE Orders
DROP TABLE InStore
DROP TABLE Driver
DROP TABLE Shift
DROP TABLE StaffPayment
DROP TABLE Ingredient
DROP TABLE Supplier
DROP TABLE MenuItem
DROP TABLE Staff
DROP TABLE Customer